matrix:
  arch:
    - 64
    - 32
  options:
    - "--enable-debug-logs"
    - ""

build:
  image: "teaci/msys$${arch}"
  pull: true
  shell: "mingw$${arch}"
  commands:
    - "mkdir -p m4"
    - "autoreconf -ifv"
    - "./configure CPPFLAGS=\"-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC\" CXXFLAGS=\"-O1\" $${options}"
    - "make -j$(nproc)"
    - "make check"

notify:
  irc:
    prefix: " lh_mouse"
    nick: tea-ci
    channel: mcfproj
    server:
      host: chat.freenode.net
      port: 6697
      tls: true
